"""Add share_id to Group model

Revision ID: ea76c8147600
Revises: 7d90cee1a45a
Create Date: 2025-10-24 11:41:09.589518

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea76c8147600'
down_revision = '7d90cee1a45a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('share_id', sa.String(length=8), nullable=False))
        batch_op.create_unique_constraint(None, ['share_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('share_id')

    # ### end Alembic commands ###
